### PR TITLE
Fix of always required field

### PR DESCRIPTION
**Pull request by snirs90**
All the fields was required event if it shouldn't be.
for example, an Email field that not required and the value if empty, the error receive is:

``` json
"errors": {
        "email": [
            "The value  is invalid for the field email."
        ],
}
```

So I just added that it should verify if the value is valid only if there is a value.

### CODE REVIEW

**Comment by amitaibu** [comment]
thanks, @RoySegall can you please add a simpleTest for this as-well.

**Comment by RoySegall** [comment]
@amitaibu I added test. Can you have a look? This commit is required for #14

**Comment by amitaibu** [comment]
needs a re-roll

**Comment by amitaibu** [comment]
- I don't see the tests

**Comment by RoySegall** [comment]
OK, i added the test.

**Comment by amitaibu** [comment]
I'm not seeing it in this PR -- https://github.com/Gizra/entity_validator/pull/12/files

**Comment by amitaibu** [comment]
oh, sorry, now I see.

**Comment by amitaibu** [comment]
If green, you can merge squash.

**Comment by RoySegall** [comment]
The tests are green. I'm merging in.

**Pull request closed without merging**
